sudo: required

services:
  - docker

script:
  - docker build -t ma3ya/python-tools .

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "travis_setting_bugfix" ]; then
      echo docker login -u $DOCKER_USER -p $DOCKER_PASS
      echo docker push ma3ya/python-tools
    fi
