sudo: required

services:
  - docker

script:
  - docker build -t ma3ya/python-tools .

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u $DOCKER_USER -p $DOCKER_PASS
      docker push ma3ya/python-tools
    fi
